name: sport_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_jailbreak_detection: ^1.10.0
  flutter_riverpod: ^2.4.0
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.4
  google_fonts: ^6.0.0
  http: ^1.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/